# Generated by Django 2.1.15 on 2020-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('taz', models.CharField(db_column='TAZ', max_length=9)),
                ('password', models.TextField(db_column='Password')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexFormModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('taz', models.CharField(db_column='TAZ', max_length=9)),
                ('tele', models.TextField(db_column='telephone')),
                ('symp', models.TextField(db_column='Symptoms')),
            ],
            options={
                'db_table': 'indexform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterFormModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('password', models.TextField(db_column='password')),
                ('Type', models.TextField(db_column='type')),
            ],
            options={
                'db_table': 'registerform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('taz', models.CharField(db_column='TAZ', max_length=9)),
                ('password', models.TextField(db_column='Password')),
            ],
            options={
                'db_table': 'worker',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CivilianModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('taz', models.CharField(db_column='TAZ', max_length=9)),
                ('age', models.IntegerField(db_column='AGE')),
                ('place', models.TextField(db_column='Place')),
                ('date', models.DateField(db_column='DATE')),
                ('religion', models.TextField(db_column='Religion')),
            ],
            options={
                'db_table': 'formcivilian',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='worker_register',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='userid', max_length=9)),
                ('name', models.TextField(db_column='name')),
                ('password', models.CharField(db_column='password', max_length=10)),
            ],
            options={
                'db_table': 'worker-register',
                'managed': True,
            },
        ),
    ]
