# Generated by Django 3.1.4 on 2020-12-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('password', models.TextField(db_column='password')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CivilianModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('age', models.IntegerField(db_column='age')),
                ('place', models.TextField(db_column='place')),
                ('date', models.DateField(db_column='date')),
                ('religion', models.TextField(db_column='religion')),
            ],
            options={
                'db_table': 'civilianform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('telephone', models.CharField(db_column='telephone', max_length=11)),
                ('symptomes', models.TextField(db_column='symptomes')),
            ],
            options={
                'db_table': 'mainpageform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterFormModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('password', models.TextField(db_column='password')),
                ('Type', models.TextField(db_column='type')),
            ],
            options={
                'db_table': 'registerform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('password', models.TextField(db_column='password')),
            ],
            options={
                'db_table': 'worker',
                'managed': False,
            },
        ),
    ]
