# Generated by Django 3.1.4 on 2020-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmainpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_column='Name')),
                ('email', models.TextField(db_column='email')),
                ('telephone', models.CharField(db_column='telephone', max_length=11)),
                ('symptomes', models.CharField(db_column='symptomes', max_length=1)),
                ('age', models.IntegerField(db_column='age')),
            ],
            options={
                'db_table': 'contactmainpage',
                'managed': False,
            },
        ),
    ]
