# Generated by Django 3.1.4 on 2020-12-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerformmodel',
            options={'managed': True},
        ),
    ]
