# Generated by Django 2.1.15 on 2021-01-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0002_patientworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('taz', models.CharField(db_column='TAZ', max_length=9)),
                ('password', models.TextField(db_column='Password')),
                ('Type', models.TextField(db_column='type')),
            ],
            options={
                'db_table': 'workers',
                'managed': True,
            },
        ),
    ]
