# Generated by Django 3.1.4 on 2020-12-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0002_contactmainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='workerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(db_column='login')),
                ('password', models.CharField(db_column='password', max_length=9)),
            ],
            options={
                'db_table': 'worker-login',
                'managed': False,
            },
        ),
    ]
