# Generated by Django 3.1.4 on 2020-12-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0002_auto_20201224_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_form',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='Name')),
                ('taz', models.CharField(db_column='taz', max_length=9)),
                ('telephone', models.CharField(db_column='telephone', max_length=11)),
                ('symptomes', models.TextField(db_column='symptomes')),
            ],
            options={
                'db_table': 'indexform',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='indexform',
        ),
    ]
