# Generated by Django 2.1.15 on 2021-01-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0002_auto_20201227_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patientworker',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=11)),
                ('taz', models.CharField(max_length=9)),
                ('workerid', models.IntegerField()),
            ],
            options={
                'db_table': 'patientworker',
                'managed': False,
            },
        ),
    ]
