# Generated by Django 3.1.4 on 2020-12-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0003_auto_20201224_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_form',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='userid', max_length=9)),
                ('password', models.CharField(db_column='password', max_length=10)),
            ],
            options={
                'db_table': 'worker-register',
                'managed': False,
            },
        ),
    ]
