# Generated by Django 2.1.15 on 2021-01-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0003_workersmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workersmodel',
            options={'managed': False},
        ),
    ]
