# Generated by Django 2.1.15 on 2021-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '0004_auto_20210102_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomesFormModel',
            fields=[
                ('ID', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('head', models.TextField(db_column='head')),
                ('hot', models.TextField(db_column='hot')),
                ('smell', models.TextField(db_column='smell')),
                ('hurts', models.TextField(db_column='hurts')),
            ],
            options={
                'db_table': 'symptomesform',
                'managed': False,
            },
        ),
    ]
