# Generated by Django 2.1.15 on 2020-12-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.DateField(db_column='days')),
                ('numbers', models.IntegerField(db_column='numbers', max_length=9)),
                ('positive', models.BooleanField(db_column='positive')),
            ],
            options={
                'db_table': 'testgrapgh',
                'managed': True,
            },
        ),
    ]
