# Generated by Django 2.1.15 on 2020-12-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my.Staticov', '1_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workerlogin',
            table='testgrapgh',
        ),
    ]
